#!/bin/bash

if [ $# -ne 1 ]
then
    echo ""
    echo "Switch to the tmux session that has a file open"
    echo "USAGE: $(basename $0) FILENAME"
    exit 1
fi

# TODO: Sanity check each value as we go...
FN=$1
PID=$(fuser ${FN} 2>&1 | awk '{print $2}')
TTY=$(readlink -f /proc/${PID}/fd/0)
TARGET=$(tmux list-panes -aF '#{pane_tty}, #{session_name}:#{window_index}' | grep "${TTY}\>" | awk '{print $2}' | head -n1)
if [ -z "$TARGET" ] ; then
  COMM=$(ps -axo 'pid,comm' | awk "/\<$PID\>/ "'{print $2}')
  echo "File is opened by $COMM PID $PID on $TTY, which is not associated with a tmux session" >&2
  exit 1
fi
tmux switch-client -t $TARGET
