#!/bin/bash

if [ $# -ne 1 ]
then
    echo ""
    echo "Switch to the tmux session that has a file open"
    echo "USAGE: $(basename $0) FILENAME"
    exit 1
fi

# TODO: Sanity check each value as we go...
FN=$1
PID=$(fuser ${FN} 2>&1 | awk '{print $2}')
TTY=$(readlink -f /proc/${PID}/fd/0)
TARGET=$(tmux list-windows -aF '#{pane_tty}, #{session_name}:#{window_index}' | grep ${TTY} | awk '{print $2}')
if [ -z "$TARGET" ] ; then
  echo "No tmux session found using TTY $TTY" >&2
  exit 1
fi
tmux switch-client -t $TARGET
